spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    user: postgres
    password: postgres
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
